-- Rulează acest fișier o singură dată în Supabase SQL Editor.
-- Fiecare rând și fiecare fotografie sunt protejate prin user_id.

create table if not exists public.receipts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  expense_date date not null,
  object_path text not null unique,
  original_name text not null,
  content_type text not null,
  size_bytes bigint not null check (size_bytes > 0 and size_bytes <= 12582912),
  created_at timestamptz not null default now()
);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  entry_date date not null,
  type text not null check (type in ('income', 'expense')),
  category text not null check (char_length(category) between 1 and 80),
  amount_cents bigint not null check (amount_cents > 0),
  notes text not null default '' check (char_length(notes) <= 500),
  receipt_id bigint references public.receipts(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists receipts_user_date_idx on public.receipts(user_id, expense_date desc);
create index if not exists transactions_user_date_idx on public.transactions(user_id, entry_date desc);
create index if not exists transactions_receipt_idx on public.transactions(receipt_id);

alter table public.receipts enable row level security;
alter table public.transactions enable row level security;

drop policy if exists "receipts_select_own" on public.receipts;
create policy "receipts_select_own" on public.receipts for select to authenticated using (auth.uid() = user_id);
drop policy if exists "receipts_insert_own" on public.receipts;
create policy "receipts_insert_own" on public.receipts for insert to authenticated with check (auth.uid() = user_id);
drop policy if exists "receipts_update_own" on public.receipts;
create policy "receipts_update_own" on public.receipts for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "receipts_delete_own" on public.receipts;
create policy "receipts_delete_own" on public.receipts for delete to authenticated using (auth.uid() = user_id);

drop policy if exists "transactions_select_own" on public.transactions;
create policy "transactions_select_own" on public.transactions for select to authenticated using (auth.uid() = user_id);
drop policy if exists "transactions_insert_own" on public.transactions;
create policy "transactions_insert_own" on public.transactions for insert to authenticated with check (
  auth.uid() = user_id
  and (receipt_id is null or exists (
    select 1 from public.receipts r where r.id = receipt_id and r.user_id = auth.uid()
  ))
);
drop policy if exists "transactions_update_own" on public.transactions;
create policy "transactions_update_own" on public.transactions for update to authenticated using (auth.uid() = user_id) with check (
  auth.uid() = user_id
  and (receipt_id is null or exists (
    select 1 from public.receipts r where r.id = receipt_id and r.user_id = auth.uid()
  ))
);
drop policy if exists "transactions_delete_own" on public.transactions;
create policy "transactions_delete_own" on public.transactions for delete to authenticated using (auth.uid() = user_id);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'receipts',
  'receipts',
  false,
  12582912,
  array['image/jpeg', 'image/png', 'image/webp', 'image/heic', 'image/heif']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "receipt_files_select_own" on storage.objects;
create policy "receipt_files_select_own" on storage.objects for select to authenticated using (
  bucket_id = 'receipts' and (storage.foldername(name))[1] = auth.uid()::text
);
drop policy if exists "receipt_files_insert_own" on storage.objects;
create policy "receipt_files_insert_own" on storage.objects for insert to authenticated with check (
  bucket_id = 'receipts' and (storage.foldername(name))[1] = auth.uid()::text
);
drop policy if exists "receipt_files_delete_own" on storage.objects;
create policy "receipt_files_delete_own" on storage.objects for delete to authenticated using (
  bucket_id = 'receipts' and (storage.foldername(name))[1] = auth.uid()::text
);
